name: cheapskate tests

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - README.md
  workflow_dispatch:

permissions:
      id-token: write
      contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
  
      - name: Az CLI login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Check account
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az account show

      - name: Create stack 1
        uses: azure/CLI@v2
        if: true
        with:
          inlineScript: |
            az stack group create \
            --name stack1 \
            --resource-group test1 \
            --template-file main.bicep \
            --deny-settings-mode 'none'

      - name: Create stack 2
        uses: azure/CLI@v2
        if: true
        with:
          inlineScript: |
            az stack group create \
            --name stack2 \
            --resource-group test2 \
            --template-file main.bicep \
            --deny-settings-mode 'none'

      - name: Exclude stacks
        shell: pwsh
        run: ${{ github.workspace }}/cheapskate.ps1
        env:
          EXCLUDE_STACKS: |
            [ 'stack1', 'stack2' ]

      - name: Delete stacks
        shell: pwsh
        run: ${{ github.workspace }}/cheapskate.ps1

